In [2]:
import numpy as np
import pandas as pd
import re
import string

import nltk
from bangla_stemmer.stemmer import stemmer
from nltk.tokenize import WhitespaceTokenizer
from nltk.tokenize import TweetTokenizer
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt

In [17]:
# read our csv...
df = pd.read_excel('youtube_comment.xlsx')
df.drop(['Unnamed: 2'], axis = 1, inplace = True)
df

                                                    text  label
0                                        ‡ßß‡ß¶‡ß¶ ‡¶§‡ßá ‡ßß‡ß¶‡ß¶ ‡¶®‡¶æ‡¶á‡¶∏    1.0
1      ‡¶Ü‡¶Æ‡¶ø ‡¶è‡¶á ‡¶™‡ßç‡¶∞‡¶•‡¶Æ ‡¶Æ‡ßá‡¶π‡¶ú‡¶æ‡¶¨‡¶ø‡¶® ‡¶ö‡ßå‡¶ß‡ßÅ‡¶∞‡ßÄ ‡¶è‡¶¨‡¶Ç ‡¶§‡¶æ‡¶®‡¶ú‡¶ø‡¶® ‡¶§‡¶ø‡¶∂‡¶æ‡¶ï‡ßá...    NaN
2      ‡¶Ü‡¶ú ‡¶Ü‡¶Æ‡¶ø ‡¶∏‡¶§‡ßç‡¶Ø‡¶ø‡¶á ‡¶ï‡¶Æ‡ßá‡¶®‡ßç‡¶ü ‡¶ï‡¶∞‡¶≤‡¶æ‡¶Æ ‡¶è‡¶ü‡¶æ ‡¶§‡¶æ‡¶®‡¶ú‡¶ø‡¶® ‡¶§‡¶ø‡¶∂‡¶æ‡¶∞ ‡¶™‡ßç...    1.0
3                           ‡¶Ö‡¶≠‡¶ø‡¶®‡¶Ø‡¶º ‡¶≠‡¶æ‡¶≤ ‡¶ï‡¶∞‡ßá‡¶õ‡ßá ‡¶∏‡¶æ‡¶¨‡¶ø‡¶≤‡¶æ ‡¶®‡ßÇ‡¶∞ üòç    1.0
4                            ‡¶∏‡¶æ‡¶¨‡¶ø‡¶≤‡¶æ ‡¶ï‡ßá ‡¶™‡ßÅ‡¶∞‡ßã ‡¶¨‡¶ø‡¶∂‡ßç‡¶∞‡ßÄ ‡¶≤‡¶æ‡¶ó‡¶≤‡ßã    0.0
...                                                  ...    ...
17969          ‡¶´‡¶æ‡¶≤‡¶§‡ßÅ ‡¶®‡¶æ‡¶ü‡¶ï ‡¶ï‡ßá ‡¶∏‡¶æ‡¶¨‡ßç‡¶¨‡¶ø‡¶∞ ‡¶Ö‡¶¨‡¶ø‡¶®‡¶Ø‡¶º ‡¶ï‡¶∞‡ßá ‡¶¨‡ßÅ‡¶ú‡¶≤‡¶æ‡¶Æ ‡¶®‡¶æ    0.0
17970          ‡¶ì‡¶∞‡ßá ‡¶Æ‡¶æ‡¶¶‡¶æ‡¶∞‡¶ö‡ßã‡¶¶ ‡¶≠‡¶æ‡¶á ‡¶∂‡ßá‡¶∑ ‡¶Æ‡ßá‡¶∂ ‡¶∏‡¶æ‡¶á‡¶ü ‡¶®‡¶æ‡¶Ø‡¶º‡ßã‡¶ï‡ßá‡¶∞ ‡¶™‡¶æ‡¶†    0.0
17971  ‡¶Ü‡¶Æ‡¶æ‡¶∞ ‡¶ú‡¶ø‡¶¨‡¶®‡ßá‡¶∞ ‡¶∏‡¶¨ ‡¶ö‡¶æ‡¶á‡¶§‡ßá ‡¶¨‡¶æ‡¶ú‡ßá ‡¶®‡¶æ‡¶ü‡¶ï ‡¶è‡¶ü‡¶æ ‡¶∏‡¶Æ‡¶Ø‡¶º‡¶ü‡¶æ ‡¶®‡¶∏‡ßç‡¶ü ...    NaN
17972         ‡¶Ü‡¶Æ‡¶æ‡¶∞ ‡¶¶‡ßá‡¶ñ‡¶æ ‡¶∏‡¶¨ ‡¶ö‡¶æ‡¶á‡¶§‡ßá ‡¶¨‡¶æ‡¶ú‡ßá ‡¶®‡¶æ‡¶ü‡¶ï ‡¶Ø‡¶§‡ßç‡¶§ ‡¶∏‡¶¨ ‡¶´‡¶æ‡¶≤‡¶§‡ßÅ    0.0
17973  ‡¶®‡¶æ‡¶ü‡¶ï‡¶ü‡¶æ ‡¶ö‡¶Æ‡ßé‡¶ï‡¶æ‡¶∞ ‡¶≤‡ßá‡¶ó‡ßá‡¶õ‡ßá ‡¶è‡¶§ ‡¶∏‡ßÅ‡¶®‡ßç‡¶¶‡¶∞ ‡¶®‡¶æ‡¶ü‡¶ï ‡¶∞‡ßá‡¶ñ‡ßá ‡¶ï‡ßá‡¶® ‡¶Ø...    1.0

[17974 rows x 2 columns]

In [18]:
df_pos = df.loc[df['label'] == 1]
df_pos

                                                    text  label
0                                        ‡ßß‡ß¶‡ß¶ ‡¶§‡ßá ‡ßß‡ß¶‡ß¶ ‡¶®‡¶æ‡¶á‡¶∏    1.0
2      ‡¶Ü‡¶ú ‡¶Ü‡¶Æ‡¶ø ‡¶∏‡¶§‡ßç‡¶Ø‡¶ø‡¶á ‡¶ï‡¶Æ‡ßá‡¶®‡ßç‡¶ü ‡¶ï‡¶∞‡¶≤‡¶æ‡¶Æ ‡¶è‡¶ü‡¶æ ‡¶§‡¶æ‡¶®‡¶ú‡¶ø‡¶® ‡¶§‡¶ø‡¶∂‡¶æ‡¶∞ ‡¶™‡ßç...    1.0
3                           ‡¶Ö‡¶≠‡¶ø‡¶®‡¶Ø‡¶º ‡¶≠‡¶æ‡¶≤ ‡¶ï‡¶∞‡ßá‡¶õ‡ßá ‡¶∏‡¶æ‡¶¨‡¶ø‡¶≤‡¶æ ‡¶®‡ßÇ‡¶∞ üòç    1.0
5                      ‡¶Ö‡¶®‡ßá‡¶ï ‡¶ï‡¶ø‡¶õ‡ßÅ ‡¶∂‡¶ø‡¶ñ‡¶æ‡¶∞ ‡¶Ü‡¶õ‡ßá ‡¶∏‡¶§‡ßç‡¶Ø‡¶ø ‡¶Ö‡¶∏‡¶æ‡¶ß‡¶æ‡¶∞‡¶£    1.0
7                                      ‡¶∏‡¶æ‡¶¨‡¶ø‡¶≤‡¶æ ‡¶®‡ßÇ‡¶∞ ‚ù§Ô∏è‚ù§Ô∏è‚ù§Ô∏è    1.0
...                                                  ...    ...
17961          ‡¶†‡ßÄ‡¶ï ‡¶¨‡¶≤‡ßá‡¶õ‡ßá‡¶® ‡¶Ö‡¶®‡ßç‡¶Ø ‡¶ï‡¶ø‡¶õ‡ßÅ‡¶∞ ‡¶¶‡ßá‡¶ñ‡¶æ‡¶∞ ‡¶ï‡ßã‡¶® ‡¶¶‡¶∞‡¶ï‡¶æ‡¶∞ ‡¶®‡¶æ‡¶á    1.0
17963  ‡¶è‡¶á ‡¶¶‡¶∞‡¶®‡ßá‡¶∞ ‡¶á‡¶Æ‡ßã‡¶∂‡¶®‡¶æ‡¶≤ ‡¶∏‡¶ø‡¶®‡¶æ‡¶Æ‡¶æ ‡¶Ø‡¶¶‡¶ø ‡¶¨‡¶æ‡¶Ç‡¶≤‡¶æ ‡¶ö‡¶≤‡¶ö‡ßç‡¶ö‡¶ø‡¶§‡ßç‡¶∞‡ßá ‡¶Æ...    1.0
17964                                               ‡¶ì‡¶Ø‡¶º‡¶æ‡¶ì    1.0
17966  ‡¶§‡¶§‡ßã‡¶ü‡¶æ ‡¶≠‡¶æ‡¶≤ ‡¶π‡¶Ø‡¶º‡¶®‡¶ø ‡¶è‡¶ï‡¶ü‡¶æ ‡¶Æ‡ßá‡¶Ø‡¶º‡ßá ‡¶Ø‡¶¶‡¶ø ‡¶è‡¶ï‡¶ü‡¶æ ‡¶õ‡ßá‡¶≤‡ßá‡¶ï‡ßá ‡¶™‡¶õ‡¶®‡ßç‡¶¶...    1.0
17973  ‡¶®‡¶æ‡¶ü‡¶ï‡¶ü‡¶æ ‡¶ö‡¶Æ‡ßé‡¶ï‡¶æ‡¶∞ ‡¶≤‡ßá‡¶ó‡ßá‡¶õ‡ßá ‡¶è‡¶§ ‡¶∏‡ßÅ‡¶®‡ßç‡¶¶‡¶∞ ‡¶®‡¶æ‡¶ü‡¶ï ‡¶∞‡ßá‡¶ñ‡ßá ‡¶ï‡ßá‡¶® ‡¶Ø...    1.0

[3408 rows x 2 columns]

In [19]:
df_neg = df.loc[df['label'] == 0]
df_neg

                                                    text  label
4                            ‡¶∏‡¶æ‡¶¨‡¶ø‡¶≤‡¶æ ‡¶ï‡ßá ‡¶™‡ßÅ‡¶∞‡ßã ‡¶¨‡¶ø‡¶∂‡ßç‡¶∞‡ßÄ ‡¶≤‡¶æ‡¶ó‡¶≤‡ßã    0.0
6                                     ‡¶¨‡¶æ‡¶≤ ‡¶á‡¶°‡¶ø‡¶ü ‡¶ï‡¶∞‡¶õ‡ßá‡¶® ‡¶≠‡¶æ‡¶á    0.0
8                       ‡¶∏‡¶æ‡¶¨‡¶ø‡¶≤‡¶æ ‡¶®‡ßÇ‡¶∞ ‡¶∞‡ßá ‡¶ö‡ßÅ‡¶®‡¶®‡¶ø‡¶∞ ‡¶Æ‡¶§ ‡¶¶‡ßá‡¶ñ‡¶æ ‡¶Ø‡¶æ‡¶Ø‡¶º    0.0
9      ‡¶¨‡¶æ‡¶π ‡¶¨‡¶æ‡¶π ‡¶ó‡¶æ‡¶®‡¶ú‡¶æ ‡¶ñ‡¶æ‡¶ì‡¶Ø‡¶º‡¶æ‡¶∞ ‡¶Ö‡¶≠‡¶ø‡¶®‡¶¨ ‡¶∂‡¶ø‡¶ï‡ßç‡¶∑‡¶æ ‡¶¶‡ßá‡¶ì‡¶Ø‡¶º‡¶æ ‡¶π‡¶á‡¶§‡¶æ‡¶õ‡ßá...    0.0
18                                  ‡¶∏‡¶æ‡¶â‡¶®‡ßç‡¶°‡¶∏ ‡¶è ‡¶≠‡¶æ‡¶≤ ‡¶∏‡¶Æ‡¶∏‡ßç‡¶Ø‡¶æ    0.0
...                                                  ...    ...
17965                                 ‡¶Ü‡¶∏‡¶≤‡ßá‡¶á ‡¶®‡¶æ‡¶ü‡¶ï‡¶ü‡¶ø ‡¶´‡¶æ‡¶≤‡¶§‡ßÅ    0.0
17967       ‡¶§‡¶æ‡¶á ‡¶¨‡¶≤‡ßá ‡¶™‡ßÅ‡¶∞‡ßÅ‡¶∑ ‡¶ú‡¶æ‡¶§‡¶ø ‡¶ï‡ßá ‡¶ö‡ßã‡¶ü ‡¶ï‡¶∞‡ßá ‡¶ï‡ßã‡¶® ‡¶ï‡¶∞‡¶æ ‡¶†‡¶ø‡¶ï ‡¶®‡¶æ    0.0
17969          ‡¶´‡¶æ‡¶≤‡¶§‡ßÅ ‡¶®‡¶æ‡¶ü‡¶ï ‡¶ï‡ßá ‡¶∏‡¶æ‡¶¨‡ßç‡¶¨‡¶ø‡¶∞ ‡¶Ö‡¶¨‡¶ø‡¶®‡¶Ø‡¶º ‡¶ï‡¶∞‡ßá ‡¶¨‡ßÅ‡¶ú‡¶≤‡¶æ‡¶Æ ‡¶®‡¶æ    0.0
17970          ‡¶ì‡¶∞‡ßá ‡¶Æ‡¶æ‡¶¶‡¶æ‡¶∞‡¶ö‡ßã‡¶¶ ‡¶≠‡¶æ‡¶á ‡¶∂‡ßá‡¶∑ ‡¶Æ‡ßá‡¶∂ ‡¶∏‡¶æ‡¶á‡¶ü ‡¶®‡¶æ‡¶Ø‡¶º‡ßã‡¶ï‡ßá‡¶∞ ‡¶™‡¶æ‡¶†    0.0
17972         ‡¶Ü‡¶Æ‡¶æ‡¶∞ ‡¶¶‡ßá‡¶ñ‡¶æ ‡¶∏‡¶¨ ‡¶ö‡¶æ‡¶á‡¶§‡ßá ‡¶¨‡¶æ‡¶ú‡ßá ‡¶®‡¶æ‡¶ü‡¶ï ‡¶Ø‡¶§‡ßç‡¶§ ‡¶∏‡¶¨ ‡¶´‡¶æ‡¶≤‡¶§‡ßÅ    0.0

[1585 rows x 2 columns]

In [20]:
all_pos_ours = []
for index, rows in df_pos.iterrows():
    all_pos_ours.append(rows.text)

all_neg_ours = []
for index, rows in df_neg.iterrows():
    all_neg_ours.append(rows.text)

In [21]:
print(len(all_pos_ours))
print(len(all_neg_ours))

3408
1585

In [17]:
with open('all_pos_ours.txt', 'w') as f:
    for item in all_pos_ours:
        f.write("%s\n" % item)

In [18]:
with open('all_neg_ours.txt', 'w') as f:
    for item in all_neg_ours:
        f.write("%s\n" % item)